- name: Install Docker
  hosts: all
  become: true
  
  tasks:
    - name: ping host
      ansible.builtin.ping:

    - name: update & upgrade on apt
      ansible.builtin.apt:
        name: "*"
        state: latest
        update_cache: yes
        cache_valid_time: 3600

    - name: remove possible old docker components
      ansible.builtin.apt:
        pkg:
          - docker.io
          - docker-doc
          - docker-compose
          - docker-compose-v2
          - podman-docker
          - containerd
          - runc
        state: absent

    - name: install gpg key prerequisites
      ansible.builtin.apt:
        pkg:
          - ca-certificates
          - curl
        state: present

    - name: create directory for docker's gpg keys
      ansible.builtin.file:
        path: /etc/apt/keyrings
        state: directory
        mode: "0755"

    - name: add docker's gpg key
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        keyring: /etc/apt/keyrings/docker.gpg
        state: present

    - name: Add docker repository
      ansible.builtin.apt_repository:
        repo: >-
          deb [arch={{ ansible_architecture }}
          signed-by=/etc/apt/keyrings/docker.gpg]
          https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable
        filename: docker
        state: present

    - name: Install docker packages
      ansible.builtin.apt:
        pkg:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present # docker installed at this point

